### ISSUE TITLE
[Bug] Windows 10 install problems

### ISSUE THREAD

**Issue by tchatterton** [deezer/spleeter#472]
## Description

I have been trying to install spleeter for over a week now and failing with numerous problems over 2 PCs running Windows 10 trying to get Spleeter to install and run.

Main problem is getting loads of conflicts. Any advice welcome - particulalry what the best version of Anaconda to try is as this seems to be the preferred environment?

## Step to reproduce

1) Used Anaconda to install - eventually worked out that I neded Python 3.6 or 3.7 - after failing to get things to work with 3.6 or 3.7 in a virtual environment, or trying to reset the whole version of Python that Anaconda was running, I tried various old versions of the Anaconda installer and settled to using Anaconda 2019.10 to get a Python 3.7 install

Have also tried installing the CUDA drivers and the -GPU option but this has addressed CUDA errors but not general package conflicts

## Output
I get screeds of conflicts.... I could post them all, but really it is loads...
They look a bit like this

Package blosc conflicts for:
anaconda==2020.02 -> pytables==3.6.1=py36h1da0976_0 -> blosc[version='>=1.16.3,<2.0a0']
pytables -> blosc[version='>=1.14.3,<2.0a0|>=1.14.4,<2.0a0|>=1.15.0,<2.0a0|>=1.16.3,<2.0a0|>=1.17.0,<2.0a0|>=1.18.1,<2.0a0']
anaconda==2020.02 -> blosc==1.16.3=h7bd577a_0

Package astroid conflicts for:
anaconda==2020.02 -> astroid==2.3.3[build='py38_0|py36_0|py37_0']
anaconda==2020.02 -> pylint==2.4.4=py36_0 -> astroid[version='>=2.3.0,<2.4']
spyder -> pylint[version='>=1.0'] -> astroid[version='>=1.4.5,<1.5.0|>=1.5.1|>=1.6,<2.0|>=2.0.0|>=2.2.0|>=2.2.0,<3|>=2.3.0,<2.4|>=2.4.0,<2.5']
pylint -> astroid[version='>=1.4.5,<1.5.0|>=1.5.1|>=1.6,<2.0|>=2.0.0|>=2.2.0|>=2.2.0,<3|>=2.3.0,<2.4|>=2.4.0,<2.5']
python-language-server -> pylint -> astroid[version='>=1.4.5,<1.5.0|>=1.5.1|>=1.6,<2.0|>=2.0.0|>=2.2.0|>=2.2.0,<3|>=2.3.0,<2.4|>=2.4.0,<2.5']

Package comtypes conflicts for:
anaconda==2020.02 -> xlwings==0.17.1=py36_0 -> comtypes
anaconda==2020.02 -> comtypes==1.1.7[build='py38_1000|py36_0|py37_0']
xlwings -> comtypes

ANd then at the end it just fails to install Spleeter

## Environment

| OS                | Windows 10 |
| Installation type | Conda           |
| RAM available     |6GB                         |
| Hardware spec     | AMD Ryzen 5           |

**Comment by eahola** [comment]
Ran into same. This fixed it for me after downgrading to python 3.7 via `conda install python=3.7.7`:

```
 conda config --add channels conda-forge
 conda update --all
 conda install spleeter-gpu
```

**Comment by mmoussallam** [comment]
Hi @tchatterton 

We've just released a new version that is compatible with Tensorflow2 and hopefully makes `spleeter` much more compatible with various Python setups. Let us know if the issue isn't fixed on your side.
